config/routes.rb
Rails.application.routes.draw do
  resources :texts

  resources :apps do
    get 'set', on: :member
    get 'download/:iso', action: 'download', on: :member, as: 'download'
    patch 'token', action: 'create_token', on: :member, as: 'token'
    get 'enabled_languages', on: :collection
  end

  resources :languages

  root 'texts#index'
end

app/models/app.rb
class App < ActiveRecord::Base
  has_and_belongs_to_many :languages
  has_many :texts

  validates :name, presence: true

  def self.find_by_token(token)
    return unless token
    App.find(token: token)
  end
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_and_belongs_to_many :apps

  scope :by_iso, -> { order('iso') }

  validates :name, :iso, presence: true
end

app/models/text.rb
class Text < ActiveRecord::Base
  belongs_to :app
  has_many :translations

  validates :literal, presence: true
  validates :literal, uniqueness: {scope: :app_id}

  def translations_available_languages
    app.languages.by_iso.map do |language|
      translations.find_by_language_id(language.id) || translations.build(language_id: language.id)
    end
  end
end

app/models/translation.rb
class Translation < ActiveRecord::Base
  belongs_to :text
  belongs_to :language

  def literal=(value)
    value.strip! if value
    super
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, :available_apps

  helper Sal::ApplicationHelper

  private

  def basic_auth
    return if ENV['HTTP_USER'].blank?

    authenticate_or_request_with_http_basic do |user, password|
      user == ENV['HTTP_USER'] && password == ENV['HTTP_PASSWORD']
    end
  end

  def available_apps
    @apps = App.all
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_app, only: [:edit, :update, :destroy, :download, :create_token]
  before_action :available_languages, only: [:new, :create, :edit, :update]

  # GET /apps
  def index
    @apps = App.all
  end

  # GET /apps/new
  def new
    @app = App.new
  end

  # GET /apps/1/set
  def set
    session[:current_app_id] = params[:id]
    redirect_to apps_path
  end

  # GET /apps/1/download/en.po
  def download
    language = Language.find_by(iso: params[:iso])

    respond_to do |format|
      format.po do
        headers['Content-Disposition'] = %(attachment; filename="#{language.iso}.po")
        render plain: Translations::PoCompiler.new(@app).for_language(language)
      end
    end
  end

  # GET /apps/enabled_languages
  def enabled_languages
    app = App.find_by(token: params[:app_token])
    if app
      render json: app.languages.map(&:iso)
    else
      render plain: '403 Forbidden', status: 403
    end
  end

  # GET /apps/1/edit
  def edit; end

  # POST /apps
  def create
    @app = App.new(app_params)

    if @app.save
      @app.languages = languages
      redirect_to apps_path, notice: 'App was successfully created.'
    else
      render :new
    end
  end

  # PATCH /apps/1/token
  def create_token
    @app.update_column :token, SecureRandom.hex(32)

    flash[:show_token] = true

    redirect_to apps_path
  end

  # PATCH/PUT /apps/1
  def update
    if @app.update(app_params)
      @app.languages = languages
      redirect_to apps_path, notice: 'App was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /apps/1
  def destroy
    @app.destroy
    redirect_to apps_path, notice: 'App was successfully destroyed.'
  end

  private

  def languages
    return [] if params[:app].blank? || params[:app][:languages].blank?
    Array(params[:app][:languages]).map { |language_id| Language.find_by_id(language_id) }.compact
  end

  def available_languages
    @languages = Language.all
  end

  def set_app
    @app = App.find(params[:id])
  end

  def app_params
    params.require(:app).permit(:name)
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: [:edit, :update, :destroy]

  # GET /languages
  def index
    @languages = Language.all
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit; end

  # POST /languages
  def create
    @language = Language.new(language_params)

    if @language.save
      redirect_to languages_path, notice: 'Language was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /languages/1
  def update
    if @language.update(language_params)
      redirect_to languages_path, notice: 'Language was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /languages/1
  def destroy
    @language.destroy
    redirect_to languages_path, notice: 'Language was successfully destroyed.'
  end

  private

  def set_language
    @language = Language.find(params[:id])
  end

  def language_params
    params.require(:language).permit!
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_current_app
  before_action :set_text, only: [:edit, :update, :destroy]

  # GET /texts
  def index
    @texts = @app.texts

    respond_to do |format|
      format.html
      format.po do
        language = Language.find_by(iso: params[:iso])
        render plain: Translations::PoCompiler.new(@app).for_language(language)
      end
    end
  end

  # GET /texts/new
  def new
    @text = @app.texts.build
  end

  # GET /texts/1/edit
  def edit; end

  # POST /texts
  def create
    @text = @app.texts.build(text_params)

    if TextTranslationsCreation.new(@text).save_with_translations(params[:translations])
      redirect_to texts_path, notice: 'Text was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /texts/1
  def update
    @text.attributes = text_params

    if TextTranslationsCreation.new(@text).save_with_translations(params[:translations])
      redirect_to texts_path, notice: 'Text was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /texts/1
  def destroy
    @text.destroy
    redirect_to texts_path, notice: 'Text was successfully destroyed.'
  end

  private

  def set_text
    @text = Text.find(params[:id])
  end

  def text_params
    params.require(:text).permit(:literal, :accepted)
  end

  def set_current_app
    @app = App.find_by(id: session[:current_app_id]) || App.find_by(token: params[:app_token])
    unless @app
      if params[:app_token] # request is from API
        render plain: '403 Forbidden', status: 403
      else
        redirect_to(apps_path, notice: "Select an app from the dropdown to edit its text strings.<br>Don't have an app? Add one!")
      end
    end
  end
end

app/helpers/app_helper.rb
module AppHelper
  def download_links(app, format)
    app.languages.map do |language|
      link_to language.iso, download_app_path(app, iso: language.iso, format: format)
    end.join(', ').html_safe
  end

  def show_token(app)
    if flash[:show_token]
      render partial: 'apps/token', locals: {app: app}
    else
      link_to 'Generate a new token for the app', token_app_path(app), method: :patch
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_app
    app = App.find_by_id(session[:current_app_id])
    app ? app.name : 'No app selected'
  end
end

app/helpers/text_helper.rb
module TextHelper
  def available_translations(text)
    text.translations.map do |translation|
      translation.language.iso if translation.literal.present?
    end.uniq.join "\n"
  end
end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <%= errors_bar @app %>
  <div class="row">
    <div class="col-sm-8">

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, :class => 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :languages %>
        <%= f.select :languages, options_from_collection_for_select(@languages, :id, :name, @app.languages.map(&:id)), {}, :class => 'form-control', :multiple => true %>
      </div>

    </div>
  </div>

  <%= f.submit 'Save', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', apps_path, class: 'btn btn-default' %>
<% end %>

app/views/apps/_token.html.erb
<p><%= app.token %></p>

<p class="label label-warning">Copy this token into a safe place ASAP! It will disappear soon.</p>

app/views/apps/edit.html.erb
<h2>Editing app</h2>

<%= render 'form' %>

app/views/apps/index.html.erb
<%= messages_bar %>

<p>
  <%= link_to 'New app', new_app_path, class: 'btn btn-default' %>
</p>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Languages</th>
      <th>Text strings</th>
      <th>PO download</th>
      <th>Token</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.name %></td>
        <td><%= app.languages.map(&:iso).join(', ') %></td>
        <td><%= app.texts.count %></td>
        <td><%= download_links(app, :po) %></td>
        <td><%= show_token(app) %></td>
        <td><%= link_to 'Edit', edit_app_path(app) %></td>
        <td><%= link_to 'Destroy', app, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/apps/new.html.erb
<h2>New app</h2>

<%= render 'form' %>

app/views/languages/_form.html.erb
<%= form_for(@language) do |f| %>
  <%= errors_bar @language %>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, :class => 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :iso, 'ISO 639-1 code' %>
        <%= f.text_field :iso, :class => 'form-control' %>
      </div>
    </div>
  </div>

  <%= f.submit 'Save', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', languages_path, :class => 'btn btn-default' %>
<% end %>

app/views/languages/edit.html.erb
<h2>Edit language</h2>

<%= render 'form' %>

app/views/languages/index.html.erb
<%= messages_bar %>

<p>
  <%= link_to 'New language', new_language_path, class: 'btn btn-default' %>
</p>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>ISO 639-1 code</th>
      <th>Apps</th>
    </tr>
  </thead>
  <tbody>
    <% @languages.each do |language| %>
      <tr>
        <td><%= link_to language.name, edit_language_path(language.id) %></td>
        <td><%= language.iso %></td>
        <td><%= language.apps.map(&:name).join(', ') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/languages/new.html.erb
<h2>New language</h2>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Interpres</title>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <header class="navbar navbar-default" role="navigation">
      <nav class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Interpres</a>
        </div>
        <ul class="nav navbar-nav">
          <%= menu_item 'languages' do %><%= link_to 'Languages', languages_path %><% end %>
          <%= menu_item 'apps' do %><%= link_to 'Apps', apps_path %><% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_app %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% @apps.each do |app| %>
                <li><%= link_to app.name, set_app_path(app) %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </nav>
    </header>

    <div class="container">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/texts/_form.html.erb
<%= form_for(@text) do |f| %>
  <%= errors_bar @text %>

  <div class="form-group">
    <%= f.label :literal, 'String' %>
    <%= f.text_area :literal, rows: 3, class: 'form-control' %>
  </div>

  <div class="checkbox">
    <label>
      <%= f.check_box :accepted %>
      Accepted?
    </label>
  </div>

  <div class="row">

    <% @text.translations_available_languages.each do |translation| %>
      <div class="col-sm-6">
        <div class="form-group">
          <%= label_tag :translations, "Translation into #{translation.language.name}" %>
          <%= text_area_tag :'translations[]', translation.literal, rows: 6, class: 'form-control' %>
        </div>
      </div>
    <% end %>

  </div>

  <%= f.submit 'Save', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', texts_path, class: 'btn btn-default' %>
<% end %>

app/views/texts/edit.html.erb
<h2>Editing text string</h2>

<%= render 'form' %>

app/views/texts/index.html.erb
<%= messages_bar %>

<p>
  <%= link_to "New text for #{@app.name}", new_text_path, class: 'btn btn-default' %>
</p>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Literal</th>
      <th>Accepted?</th>
      <th>Translated into</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @texts.each do |text| %>
      <tr>
        <td><%= text.literal %></td>
        <td><%= text.accepted %></td>
        <td><%= available_translations(text) %></td>
        <td><%= link_to 'Edit', edit_text_path(text) %></td>
        <td><%= link_to 'Destroy', text, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/texts/new.html.erb
<h2>New text string</h2>

<%= render 'form' %>